/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BalkanRouteRouteImport } from './routes/balkan-route'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as OtherPeaksRouteImport } from './routes/other-peaks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapPeaksDotxmlRouteImport } from './routes/sitemap-peaks[.]xml'
import { Route as StartRouteImport } from './routes/start'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WhereRouteImport } from './routes/where'
import { Route as AccountLinkedRouteImport } from './routes/account/linked'
import { Route as AccountPasswordRouteImport } from './routes/account/password'
import { Route as AdminPeakbaggerImportRouteImport } from './routes/admin/peakbagger-import'
import { Route as AdminYoutubeStatsRouteImport } from './routes/admin/youtube-stats'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityAdventuresRouteImport } from './routes/community/adventures'
import { Route as CommunityAppearanceRouteImport } from './routes/community/appearance'
import { Route as CommunityAscentsRouteImport } from './routes/community/ascents'
import { Route as CommunityBasecampRouteImport } from './routes/community/basecamp'
import { Route as CommunityDefinitionsRouteImport } from './routes/community/definitions'
import { Route as CommunityFollowingRouteImport } from './routes/community/following'
import { Route as CommunityFrontrunnersRouteImport } from './routes/community/frontrunners'
import { Route as CommunityHelpRouteImport } from './routes/community/help'
import { Route as CommunityImportPeaksRouteImport } from './routes/community/import-peaks'
import { Route as CommunityIntroRouteImport } from './routes/community/intro'
import { Route as CommunityLeaderboardRouteImport } from './routes/community/leaderboard'
import { Route as CommunityListBuilderRouteImport } from './routes/community/list-builder'
import { Route as CommunityListsRouteImport } from './routes/community/lists'
import { Route as CommunityModerationRouteImport } from './routes/community/moderation'
import { Route as CommunityMyAdventuresRouteImport } from './routes/community/my-adventures'
import { Route as CommunityPhotoVoteRouteImport } from './routes/community/photo-vote'
import { Route as CommunitySettingsRouteImport } from './routes/community/settings'
import { Route as CommunitySupportRouteImport } from './routes/community/support'
import { Route as CommunityWallRouteImport } from './routes/community/wall'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesGuideSlugRouteImport } from './routes/guides/$guideSlug'
import { Route as HighestMountainsIndexRouteImport } from './routes/highest-mountains/index'
import { Route as HighestMountainsContinentSlugRouteImport } from './routes/highest-mountains/$continentSlug'
import { Route as PeakCountrySlugRouteImport } from './routes/peak/$countrySlug'
import { Route as PeakScafellPikeRouteImport } from './routes/peak/scafell-pike'
import { Route as PeaksIndexRouteImport } from './routes/peaks.index'
import { Route as PeaksPeakIdRouteImport } from './routes/peaks.$peakId'
import { Route as CommunityChallengeMapIdRouteImport } from './routes/community/challenge-map.$id'
import { Route as CommunityMembersIndexRouteImport } from './routes/community/members/index'
import { Route as CommunityMembersIdRouteImport } from './routes/community/members/$id'
import { Route as CommunityNotificationsIndexRouteImport } from './routes/community/notifications/index'
import { Route as CommunityNotificationsSettingsRouteImport } from './routes/community/notifications/settings'
import { Route as PeaksCountryCodeRouteImport } from './routes/peaks.country.$code'
import { Route as ApiPublicHooksScrapePeakbaggerRouteImport } from './routes/api/public/hooks/scrape-peakbagger'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BalkanRouteRoute = BalkanRouteRouteImport.update({
  id: '/balkan-route',
  path: '/balkan-route',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherPeaksRoute = OtherPeaksRouteImport.update({
  id: '/other-peaks',
  path: '/other-peaks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPeaksDotxmlRoute = SitemapPeaksDotxmlRouteImport.update({
  id: '/sitemap-peaks.xml',
  path: '/sitemap-peaks.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereRoute = WhereRouteImport.update({
  id: '/where',
  path: '/where',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLinkedRoute = AccountLinkedRouteImport.update({
  id: '/account/linked',
  path: '/account/linked',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeakbaggerImportRoute = AdminPeakbaggerImportRouteImport.update({
  id: '/admin/peakbagger-import',
  path: '/admin/peakbagger-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYoutubeStatsRoute = AdminYoutubeStatsRouteImport.update({
  id: '/admin/youtube-stats',
  path: '/admin/youtube-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAdventuresRoute = CommunityAdventuresRouteImport.update({
  id: '/community/adventures',
  path: '/community/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAppearanceRoute = CommunityAppearanceRouteImport.update({
  id: '/community/appearance',
  path: '/community/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAscentsRoute = CommunityAscentsRouteImport.update({
  id: '/community/ascents',
  path: '/community/ascents',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityBasecampRoute = CommunityBasecampRouteImport.update({
  id: '/community/basecamp',
  path: '/community/basecamp',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityDefinitionsRoute = CommunityDefinitionsRouteImport.update({
  id: '/community/definitions',
  path: '/community/definitions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFollowingRoute = CommunityFollowingRouteImport.update({
  id: '/community/following',
  path: '/community/following',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFrontrunnersRoute = CommunityFrontrunnersRouteImport.update({
  id: '/community/frontrunners',
  path: '/community/frontrunners',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityHelpRoute = CommunityHelpRouteImport.update({
  id: '/community/help',
  path: '/community/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityImportPeaksRoute = CommunityImportPeaksRouteImport.update({
  id: '/community/import-peaks',
  path: '/community/import-peaks',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIntroRoute = CommunityIntroRouteImport.update({
  id: '/community/intro',
  path: '/community/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLeaderboardRoute = CommunityLeaderboardRouteImport.update({
  id: '/community/leaderboard',
  path: '/community/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityListBuilderRoute = CommunityListBuilderRouteImport.update({
  id: '/community/list-builder',
  path: '/community/list-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityListsRoute = CommunityListsRouteImport.update({
  id: '/community/lists',
  path: '/community/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityModerationRoute = CommunityModerationRouteImport.update({
  id: '/community/moderation',
  path: '/community/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMyAdventuresRoute = CommunityMyAdventuresRouteImport.update({
  id: '/community/my-adventures',
  path: '/community/my-adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPhotoVoteRoute = CommunityPhotoVoteRouteImport.update({
  id: '/community/photo-vote',
  path: '/community/photo-vote',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySettingsRoute = CommunitySettingsRouteImport.update({
  id: '/community/settings',
  path: '/community/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySupportRoute = CommunitySupportRouteImport.update({
  id: '/community/support',
  path: '/community/support',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityWallRoute = CommunityWallRouteImport.update({
  id: '/community/wall',
  path: '/community/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideSlugRoute = GuidesGuideSlugRouteImport.update({
  id: '/guides/$guideSlug',
  path: '/guides/$guideSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const HighestMountainsIndexRoute = HighestMountainsIndexRouteImport.update({
  id: '/highest-mountains/',
  path: '/highest-mountains/',
  getParentRoute: () => rootRouteImport,
} as any)
const HighestMountainsContinentSlugRoute =
  HighestMountainsContinentSlugRouteImport.update({
    id: '/highest-mountains/$continentSlug',
    path: '/highest-mountains/$continentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PeakCountrySlugRoute = PeakCountrySlugRouteImport.update({
  id: '/peak/$countrySlug',
  path: '/peak/$countrySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeakScafellPikeRoute = PeakScafellPikeRouteImport.update({
  id: '/peak/scafell-pike',
  path: '/peak/scafell-pike',
  getParentRoute: () => rootRouteImport,
} as any)
const PeaksIndexRoute = PeaksIndexRouteImport.update({
  id: '/peaks/',
  path: '/peaks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeaksPeakIdRoute = PeaksPeakIdRouteImport.update({
  id: '/peaks/$peakId',
  path: '/peaks/$peakId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityChallengeMapIdRoute = CommunityChallengeMapIdRouteImport.update({
  id: '/community/challenge-map/$id',
  path: '/community/challenge-map/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMembersIndexRoute = CommunityMembersIndexRouteImport.update({
  id: '/community/members/',
  path: '/community/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMembersIdRoute = CommunityMembersIdRouteImport.update({
  id: '/community/members/$id',
  path: '/community/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNotificationsIndexRoute =
  CommunityNotificationsIndexRouteImport.update({
    id: '/community/notifications/',
    path: '/community/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunityNotificationsSettingsRoute =
  CommunityNotificationsSettingsRouteImport.update({
    id: '/community/notifications/settings',
    path: '/community/notifications/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const PeaksCountryCodeRoute = PeaksCountryCodeRouteImport.update({
  id: '/peaks/country/$code',
  path: '/peaks/country/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapePeakbaggerRoute =
  ApiPublicHooksScrapePeakbaggerRouteImport.update({
    id: '/api/public/hooks/scrape-peakbagger',
    path: '/api/public/hooks/scrape-peakbagger',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balkan-route': typeof BalkanRouteRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/other-peaks': typeof OtherPeaksRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-peaks.xml': typeof SitemapPeaksDotxmlRoute
  '/start': typeof StartRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/where': typeof WhereRoute
  '/account/linked': typeof AccountLinkedRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/peakbagger-import': typeof AdminPeakbaggerImportRoute
  '/admin/youtube-stats': typeof AdminYoutubeStatsRoute
  '/community/adventures': typeof CommunityAdventuresRoute
  '/community/appearance': typeof CommunityAppearanceRoute
  '/community/ascents': typeof CommunityAscentsRoute
  '/community/basecamp': typeof CommunityBasecampRoute
  '/community/definitions': typeof CommunityDefinitionsRoute
  '/community/following': typeof CommunityFollowingRoute
  '/community/frontrunners': typeof CommunityFrontrunnersRoute
  '/community/help': typeof CommunityHelpRoute
  '/community/import-peaks': typeof CommunityImportPeaksRoute
  '/community/intro': typeof CommunityIntroRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/community/list-builder': typeof CommunityListBuilderRoute
  '/community/lists': typeof CommunityListsRoute
  '/community/moderation': typeof CommunityModerationRoute
  '/community/my-adventures': typeof CommunityMyAdventuresRoute
  '/community/photo-vote': typeof CommunityPhotoVoteRoute
  '/community/settings': typeof CommunitySettingsRoute
  '/community/support': typeof CommunitySupportRoute
  '/community/wall': typeof CommunityWallRoute
  '/guides/$guideSlug': typeof GuidesGuideSlugRoute
  '/highest-mountains/$continentSlug': typeof HighestMountainsContinentSlugRoute
  '/peak/$countrySlug': typeof PeakCountrySlugRoute
  '/peak/scafell-pike': typeof PeakScafellPikeRoute
  '/peaks/$peakId': typeof PeaksPeakIdRoute
  '/community/': typeof CommunityIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/highest-mountains/': typeof HighestMountainsIndexRoute
  '/peaks/': typeof PeaksIndexRoute
  '/community/challenge-map/$id': typeof CommunityChallengeMapIdRoute
  '/community/members/$id': typeof CommunityMembersIdRoute
  '/community/notifications/settings': typeof CommunityNotificationsSettingsRoute
  '/peaks/country/$code': typeof PeaksCountryCodeRoute
  '/community/members/': typeof CommunityMembersIndexRoute
  '/community/notifications/': typeof CommunityNotificationsIndexRoute
  '/api/public/hooks/scrape-peakbagger': typeof ApiPublicHooksScrapePeakbaggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balkan-route': typeof BalkanRouteRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/other-peaks': typeof OtherPeaksRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-peaks.xml': typeof SitemapPeaksDotxmlRoute
  '/start': typeof StartRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/where': typeof WhereRoute
  '/account/linked': typeof AccountLinkedRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/peakbagger-import': typeof AdminPeakbaggerImportRoute
  '/admin/youtube-stats': typeof AdminYoutubeStatsRoute
  '/community/adventures': typeof CommunityAdventuresRoute
  '/community/appearance': typeof CommunityAppearanceRoute
  '/community/ascents': typeof CommunityAscentsRoute
  '/community/basecamp': typeof CommunityBasecampRoute
  '/community/definitions': typeof CommunityDefinitionsRoute
  '/community/following': typeof CommunityFollowingRoute
  '/community/frontrunners': typeof CommunityFrontrunnersRoute
  '/community/help': typeof CommunityHelpRoute
  '/community/import-peaks': typeof CommunityImportPeaksRoute
  '/community/intro': typeof CommunityIntroRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/community/list-builder': typeof CommunityListBuilderRoute
  '/community/lists': typeof CommunityListsRoute
  '/community/moderation': typeof CommunityModerationRoute
  '/community/my-adventures': typeof CommunityMyAdventuresRoute
  '/community/photo-vote': typeof CommunityPhotoVoteRoute
  '/community/settings': typeof CommunitySettingsRoute
  '/community/support': typeof CommunitySupportRoute
  '/community/wall': typeof CommunityWallRoute
  '/guides/$guideSlug': typeof GuidesGuideSlugRoute
  '/highest-mountains/$continentSlug': typeof HighestMountainsContinentSlugRoute
  '/peak/$countrySlug': typeof PeakCountrySlugRoute
  '/peak/scafell-pike': typeof PeakScafellPikeRoute
  '/peaks/$peakId': typeof PeaksPeakIdRoute
  '/community': typeof CommunityIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/highest-mountains': typeof HighestMountainsIndexRoute
  '/peaks': typeof PeaksIndexRoute
  '/community/challenge-map/$id': typeof CommunityChallengeMapIdRoute
  '/community/members/$id': typeof CommunityMembersIdRoute
  '/community/notifications/settings': typeof CommunityNotificationsSettingsRoute
  '/peaks/country/$code': typeof PeaksCountryCodeRoute
  '/community/members': typeof CommunityMembersIndexRoute
  '/community/notifications': typeof CommunityNotificationsIndexRoute
  '/api/public/hooks/scrape-peakbagger': typeof ApiPublicHooksScrapePeakbaggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balkan-route': typeof BalkanRouteRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/other-peaks': typeof OtherPeaksRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-peaks.xml': typeof SitemapPeaksDotxmlRoute
  '/start': typeof StartRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/where': typeof WhereRoute
  '/account/linked': typeof AccountLinkedRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/peakbagger-import': typeof AdminPeakbaggerImportRoute
  '/admin/youtube-stats': typeof AdminYoutubeStatsRoute
  '/community/adventures': typeof CommunityAdventuresRoute
  '/community/appearance': typeof CommunityAppearanceRoute
  '/community/ascents': typeof CommunityAscentsRoute
  '/community/basecamp': typeof CommunityBasecampRoute
  '/community/definitions': typeof CommunityDefinitionsRoute
  '/community/following': typeof CommunityFollowingRoute
  '/community/frontrunners': typeof CommunityFrontrunnersRoute
  '/community/help': typeof CommunityHelpRoute
  '/community/import-peaks': typeof CommunityImportPeaksRoute
  '/community/intro': typeof CommunityIntroRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/community/list-builder': typeof CommunityListBuilderRoute
  '/community/lists': typeof CommunityListsRoute
  '/community/moderation': typeof CommunityModerationRoute
  '/community/my-adventures': typeof CommunityMyAdventuresRoute
  '/community/photo-vote': typeof CommunityPhotoVoteRoute
  '/community/settings': typeof CommunitySettingsRoute
  '/community/support': typeof CommunitySupportRoute
  '/community/wall': typeof CommunityWallRoute
  '/guides/$guideSlug': typeof GuidesGuideSlugRoute
  '/highest-mountains/$continentSlug': typeof HighestMountainsContinentSlugRoute
  '/peak/$countrySlug': typeof PeakCountrySlugRoute
  '/peak/scafell-pike': typeof PeakScafellPikeRoute
  '/peaks/$peakId': typeof PeaksPeakIdRoute
  '/community/': typeof CommunityIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/highest-mountains/': typeof HighestMountainsIndexRoute
  '/peaks/': typeof PeaksIndexRoute
  '/community/challenge-map/$id': typeof CommunityChallengeMapIdRoute
  '/community/members/$id': typeof CommunityMembersIdRoute
  '/community/notifications/settings': typeof CommunityNotificationsSettingsRoute
  '/peaks/country/$code': typeof PeaksCountryCodeRoute
  '/community/members/': typeof CommunityMembersIndexRoute
  '/community/notifications/': typeof CommunityNotificationsIndexRoute
  '/api/public/hooks/scrape-peakbagger': typeof ApiPublicHooksScrapePeakbaggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/balkan-route'
    | '/featured'
    | '/latest'
    | '/other-peaks'
    | '/privacy'
    | '/sitemap-peaks.xml'
    | '/start'
    | '/support'
    | '/team'
    | '/where'
    | '/account/linked'
    | '/account/password'
    | '/admin/peakbagger-import'
    | '/admin/youtube-stats'
    | '/community/adventures'
    | '/community/appearance'
    | '/community/ascents'
    | '/community/basecamp'
    | '/community/definitions'
    | '/community/following'
    | '/community/frontrunners'
    | '/community/help'
    | '/community/import-peaks'
    | '/community/intro'
    | '/community/leaderboard'
    | '/community/list-builder'
    | '/community/lists'
    | '/community/moderation'
    | '/community/my-adventures'
    | '/community/photo-vote'
    | '/community/settings'
    | '/community/support'
    | '/community/wall'
    | '/guides/$guideSlug'
    | '/highest-mountains/$continentSlug'
    | '/peak/$countrySlug'
    | '/peak/scafell-pike'
    | '/peaks/$peakId'
    | '/community/'
    | '/guides/'
    | '/highest-mountains/'
    | '/peaks/'
    | '/community/challenge-map/$id'
    | '/community/members/$id'
    | '/community/notifications/settings'
    | '/peaks/country/$code'
    | '/community/members/'
    | '/community/notifications/'
    | '/api/public/hooks/scrape-peakbagger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/balkan-route'
    | '/featured'
    | '/latest'
    | '/other-peaks'
    | '/privacy'
    | '/sitemap-peaks.xml'
    | '/start'
    | '/support'
    | '/team'
    | '/where'
    | '/account/linked'
    | '/account/password'
    | '/admin/peakbagger-import'
    | '/admin/youtube-stats'
    | '/community/adventures'
    | '/community/appearance'
    | '/community/ascents'
    | '/community/basecamp'
    | '/community/definitions'
    | '/community/following'
    | '/community/frontrunners'
    | '/community/help'
    | '/community/import-peaks'
    | '/community/intro'
    | '/community/leaderboard'
    | '/community/list-builder'
    | '/community/lists'
    | '/community/moderation'
    | '/community/my-adventures'
    | '/community/photo-vote'
    | '/community/settings'
    | '/community/support'
    | '/community/wall'
    | '/guides/$guideSlug'
    | '/highest-mountains/$continentSlug'
    | '/peak/$countrySlug'
    | '/peak/scafell-pike'
    | '/peaks/$peakId'
    | '/community'
    | '/guides'
    | '/highest-mountains'
    | '/peaks'
    | '/community/challenge-map/$id'
    | '/community/members/$id'
    | '/community/notifications/settings'
    | '/peaks/country/$code'
    | '/community/members'
    | '/community/notifications'
    | '/api/public/hooks/scrape-peakbagger'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/balkan-route'
    | '/featured'
    | '/latest'
    | '/other-peaks'
    | '/privacy'
    | '/sitemap-peaks.xml'
    | '/start'
    | '/support'
    | '/team'
    | '/where'
    | '/account/linked'
    | '/account/password'
    | '/admin/peakbagger-import'
    | '/admin/youtube-stats'
    | '/community/adventures'
    | '/community/appearance'
    | '/community/ascents'
    | '/community/basecamp'
    | '/community/definitions'
    | '/community/following'
    | '/community/frontrunners'
    | '/community/help'
    | '/community/import-peaks'
    | '/community/intro'
    | '/community/leaderboard'
    | '/community/list-builder'
    | '/community/lists'
    | '/community/moderation'
    | '/community/my-adventures'
    | '/community/photo-vote'
    | '/community/settings'
    | '/community/support'
    | '/community/wall'
    | '/guides/$guideSlug'
    | '/highest-mountains/$continentSlug'
    | '/peak/$countrySlug'
    | '/peak/scafell-pike'
    | '/peaks/$peakId'
    | '/community/'
    | '/guides/'
    | '/highest-mountains/'
    | '/peaks/'
    | '/community/challenge-map/$id'
    | '/community/members/$id'
    | '/community/notifications/settings'
    | '/peaks/country/$code'
    | '/community/members/'
    | '/community/notifications/'
    | '/api/public/hooks/scrape-peakbagger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BalkanRouteRoute: typeof BalkanRouteRoute
  FeaturedRoute: typeof FeaturedRoute
  LatestRoute: typeof LatestRoute
  OtherPeaksRoute: typeof OtherPeaksRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapPeaksDotxmlRoute: typeof SitemapPeaksDotxmlRoute
  StartRoute: typeof StartRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  WhereRoute: typeof WhereRoute
  AccountLinkedRoute: typeof AccountLinkedRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
  AdminPeakbaggerImportRoute: typeof AdminPeakbaggerImportRoute
  AdminYoutubeStatsRoute: typeof AdminYoutubeStatsRoute
  CommunityAdventuresRoute: typeof CommunityAdventuresRoute
  CommunityAppearanceRoute: typeof CommunityAppearanceRoute
  CommunityAscentsRoute: typeof CommunityAscentsRoute
  CommunityBasecampRoute: typeof CommunityBasecampRoute
  CommunityDefinitionsRoute: typeof CommunityDefinitionsRoute
  CommunityFollowingRoute: typeof CommunityFollowingRoute
  CommunityFrontrunnersRoute: typeof CommunityFrontrunnersRoute
  CommunityHelpRoute: typeof CommunityHelpRoute
  CommunityImportPeaksRoute: typeof CommunityImportPeaksRoute
  CommunityIntroRoute: typeof CommunityIntroRoute
  CommunityLeaderboardRoute: typeof CommunityLeaderboardRoute
  CommunityListBuilderRoute: typeof CommunityListBuilderRoute
  CommunityListsRoute: typeof CommunityListsRoute
  CommunityModerationRoute: typeof CommunityModerationRoute
  CommunityMyAdventuresRoute: typeof CommunityMyAdventuresRoute
  CommunityPhotoVoteRoute: typeof CommunityPhotoVoteRoute
  CommunitySettingsRoute: typeof CommunitySettingsRoute
  CommunitySupportRoute: typeof CommunitySupportRoute
  CommunityWallRoute: typeof CommunityWallRoute
  GuidesGuideSlugRoute: typeof GuidesGuideSlugRoute
  HighestMountainsContinentSlugRoute: typeof HighestMountainsContinentSlugRoute
  PeakCountrySlugRoute: typeof PeakCountrySlugRoute
  PeakScafellPikeRoute: typeof PeakScafellPikeRoute
  PeaksPeakIdRoute: typeof PeaksPeakIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  HighestMountainsIndexRoute: typeof HighestMountainsIndexRoute
  PeaksIndexRoute: typeof PeaksIndexRoute
  CommunityChallengeMapIdRoute: typeof CommunityChallengeMapIdRoute
  CommunityMembersIdRoute: typeof CommunityMembersIdRoute
  CommunityNotificationsSettingsRoute: typeof CommunityNotificationsSettingsRoute
  PeaksCountryCodeRoute: typeof PeaksCountryCodeRoute
  CommunityMembersIndexRoute: typeof CommunityMembersIndexRoute
  CommunityNotificationsIndexRoute: typeof CommunityNotificationsIndexRoute
  ApiPublicHooksScrapePeakbaggerRoute: typeof ApiPublicHooksScrapePeakbaggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balkan-route': {
      id: '/balkan-route'
      path: '/balkan-route'
      fullPath: '/balkan-route'
      preLoaderRoute: typeof BalkanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-peaks': {
      id: '/other-peaks'
      path: '/other-peaks'
      fullPath: '/other-peaks'
      preLoaderRoute: typeof OtherPeaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-peaks.xml': {
      id: '/sitemap-peaks.xml'
      path: '/sitemap-peaks.xml'
      fullPath: '/sitemap-peaks.xml'
      preLoaderRoute: typeof SitemapPeaksDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where': {
      id: '/where'
      path: '/where'
      fullPath: '/where'
      preLoaderRoute: typeof WhereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/linked': {
      id: '/account/linked'
      path: '/account/linked'
      fullPath: '/account/linked'
      preLoaderRoute: typeof AccountLinkedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password': {
      id: '/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peakbagger-import': {
      id: '/admin/peakbagger-import'
      path: '/admin/peakbagger-import'
      fullPath: '/admin/peakbagger-import'
      preLoaderRoute: typeof AdminPeakbaggerImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/youtube-stats': {
      id: '/admin/youtube-stats'
      path: '/admin/youtube-stats'
      fullPath: '/admin/youtube-stats'
      preLoaderRoute: typeof AdminYoutubeStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/adventures': {
      id: '/community/adventures'
      path: '/community/adventures'
      fullPath: '/community/adventures'
      preLoaderRoute: typeof CommunityAdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/appearance': {
      id: '/community/appearance'
      path: '/community/appearance'
      fullPath: '/community/appearance'
      preLoaderRoute: typeof CommunityAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/ascents': {
      id: '/community/ascents'
      path: '/community/ascents'
      fullPath: '/community/ascents'
      preLoaderRoute: typeof CommunityAscentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/basecamp': {
      id: '/community/basecamp'
      path: '/community/basecamp'
      fullPath: '/community/basecamp'
      preLoaderRoute: typeof CommunityBasecampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/definitions': {
      id: '/community/definitions'
      path: '/community/definitions'
      fullPath: '/community/definitions'
      preLoaderRoute: typeof CommunityDefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/following': {
      id: '/community/following'
      path: '/community/following'
      fullPath: '/community/following'
      preLoaderRoute: typeof CommunityFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/frontrunners': {
      id: '/community/frontrunners'
      path: '/community/frontrunners'
      fullPath: '/community/frontrunners'
      preLoaderRoute: typeof CommunityFrontrunnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/help': {
      id: '/community/help'
      path: '/community/help'
      fullPath: '/community/help'
      preLoaderRoute: typeof CommunityHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/import-peaks': {
      id: '/community/import-peaks'
      path: '/community/import-peaks'
      fullPath: '/community/import-peaks'
      preLoaderRoute: typeof CommunityImportPeaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/intro': {
      id: '/community/intro'
      path: '/community/intro'
      fullPath: '/community/intro'
      preLoaderRoute: typeof CommunityIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/leaderboard': {
      id: '/community/leaderboard'
      path: '/community/leaderboard'
      fullPath: '/community/leaderboard'
      preLoaderRoute: typeof CommunityLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/list-builder': {
      id: '/community/list-builder'
      path: '/community/list-builder'
      fullPath: '/community/list-builder'
      preLoaderRoute: typeof CommunityListBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/lists': {
      id: '/community/lists'
      path: '/community/lists'
      fullPath: '/community/lists'
      preLoaderRoute: typeof CommunityListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/moderation': {
      id: '/community/moderation'
      path: '/community/moderation'
      fullPath: '/community/moderation'
      preLoaderRoute: typeof CommunityModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/my-adventures': {
      id: '/community/my-adventures'
      path: '/community/my-adventures'
      fullPath: '/community/my-adventures'
      preLoaderRoute: typeof CommunityMyAdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/photo-vote': {
      id: '/community/photo-vote'
      path: '/community/photo-vote'
      fullPath: '/community/photo-vote'
      preLoaderRoute: typeof CommunityPhotoVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/settings': {
      id: '/community/settings'
      path: '/community/settings'
      fullPath: '/community/settings'
      preLoaderRoute: typeof CommunitySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/support': {
      id: '/community/support'
      path: '/community/support'
      fullPath: '/community/support'
      preLoaderRoute: typeof CommunitySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/wall': {
      id: '/community/wall'
      path: '/community/wall'
      fullPath: '/community/wall'
      preLoaderRoute: typeof CommunityWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideSlug': {
      id: '/guides/$guideSlug'
      path: '/guides/$guideSlug'
      fullPath: '/guides/$guideSlug'
      preLoaderRoute: typeof GuidesGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highest-mountains/': {
      id: '/highest-mountains/'
      path: '/highest-mountains'
      fullPath: '/highest-mountains/'
      preLoaderRoute: typeof HighestMountainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highest-mountains/$continentSlug': {
      id: '/highest-mountains/$continentSlug'
      path: '/highest-mountains/$continentSlug'
      fullPath: '/highest-mountains/$continentSlug'
      preLoaderRoute: typeof HighestMountainsContinentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peak/$countrySlug': {
      id: '/peak/$countrySlug'
      path: '/peak/$countrySlug'
      fullPath: '/peak/$countrySlug'
      preLoaderRoute: typeof PeakCountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peak/scafell-pike': {
      id: '/peak/scafell-pike'
      path: '/peak/scafell-pike'
      fullPath: '/peak/scafell-pike'
      preLoaderRoute: typeof PeakScafellPikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peaks/': {
      id: '/peaks/'
      path: '/peaks'
      fullPath: '/peaks/'
      preLoaderRoute: typeof PeaksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peaks/$peakId': {
      id: '/peaks/$peakId'
      path: '/peaks/$peakId'
      fullPath: '/peaks/$peakId'
      preLoaderRoute: typeof PeaksPeakIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/challenge-map/$id': {
      id: '/community/challenge-map/$id'
      path: '/community/challenge-map/$id'
      fullPath: '/community/challenge-map/$id'
      preLoaderRoute: typeof CommunityChallengeMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/members/': {
      id: '/community/members/'
      path: '/community/members'
      fullPath: '/community/members/'
      preLoaderRoute: typeof CommunityMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/members/$id': {
      id: '/community/members/$id'
      path: '/community/members/$id'
      fullPath: '/community/members/$id'
      preLoaderRoute: typeof CommunityMembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/notifications/': {
      id: '/community/notifications/'
      path: '/community/notifications'
      fullPath: '/community/notifications/'
      preLoaderRoute: typeof CommunityNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/notifications/settings': {
      id: '/community/notifications/settings'
      path: '/community/notifications/settings'
      fullPath: '/community/notifications/settings'
      preLoaderRoute: typeof CommunityNotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peaks/country/$code': {
      id: '/peaks/country/$code'
      path: '/peaks/country/$code'
      fullPath: '/peaks/country/$code'
      preLoaderRoute: typeof PeaksCountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-peakbagger': {
      id: '/api/public/hooks/scrape-peakbagger'
      path: '/api/public/hooks/scrape-peakbagger'
      fullPath: '/api/public/hooks/scrape-peakbagger'
      preLoaderRoute: typeof ApiPublicHooksScrapePeakbaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BalkanRouteRoute: BalkanRouteRoute,
  FeaturedRoute: FeaturedRoute,
  LatestRoute: LatestRoute,
  OtherPeaksRoute: OtherPeaksRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapPeaksDotxmlRoute: SitemapPeaksDotxmlRoute,
  StartRoute: StartRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  WhereRoute: WhereRoute,
  AccountLinkedRoute: AccountLinkedRoute,
  AccountPasswordRoute: AccountPasswordRoute,
  AdminPeakbaggerImportRoute: AdminPeakbaggerImportRoute,
  AdminYoutubeStatsRoute: AdminYoutubeStatsRoute,
  CommunityAdventuresRoute: CommunityAdventuresRoute,
  CommunityAppearanceRoute: CommunityAppearanceRoute,
  CommunityAscentsRoute: CommunityAscentsRoute,
  CommunityBasecampRoute: CommunityBasecampRoute,
  CommunityDefinitionsRoute: CommunityDefinitionsRoute,
  CommunityFollowingRoute: CommunityFollowingRoute,
  CommunityFrontrunnersRoute: CommunityFrontrunnersRoute,
  CommunityHelpRoute: CommunityHelpRoute,
  CommunityImportPeaksRoute: CommunityImportPeaksRoute,
  CommunityIntroRoute: CommunityIntroRoute,
  CommunityLeaderboardRoute: CommunityLeaderboardRoute,
  CommunityListBuilderRoute: CommunityListBuilderRoute,
  CommunityListsRoute: CommunityListsRoute,
  CommunityModerationRoute: CommunityModerationRoute,
  CommunityMyAdventuresRoute: CommunityMyAdventuresRoute,
  CommunityPhotoVoteRoute: CommunityPhotoVoteRoute,
  CommunitySettingsRoute: CommunitySettingsRoute,
  CommunitySupportRoute: CommunitySupportRoute,
  CommunityWallRoute: CommunityWallRoute,
  GuidesGuideSlugRoute: GuidesGuideSlugRoute,
  HighestMountainsContinentSlugRoute: HighestMountainsContinentSlugRoute,
  PeakCountrySlugRoute: PeakCountrySlugRoute,
  PeakScafellPikeRoute: PeakScafellPikeRoute,
  PeaksPeakIdRoute: PeaksPeakIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  HighestMountainsIndexRoute: HighestMountainsIndexRoute,
  PeaksIndexRoute: PeaksIndexRoute,
  CommunityChallengeMapIdRoute: CommunityChallengeMapIdRoute,
  CommunityMembersIdRoute: CommunityMembersIdRoute,
  CommunityNotificationsSettingsRoute: CommunityNotificationsSettingsRoute,
  PeaksCountryCodeRoute: PeaksCountryCodeRoute,
  CommunityMembersIndexRoute: CommunityMembersIndexRoute,
  CommunityNotificationsIndexRoute: CommunityNotificationsIndexRoute,
  ApiPublicHooksScrapePeakbaggerRoute: ApiPublicHooksScrapePeakbaggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
